variable "ENV" {}
variable "VPC_CIDR_MAIN" {}
variable "VPC_CIDR_ADDON" {}
variable "PUBLIC_SUBNETS" {}
variable "PRIVATE_SUBNETS" {}
variable "AZS" {}
variable "VPC_ID_DEFAULT" {}
variable "VPC_CIDR_DEFAULT" {}
variable INTERNAL_HOSTED_ZONEID {}